dist: trusty
language: node_js
node_js:
  - "12"
services:
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
script:
  - npm run start:docker-ci
