version: '3.7'
services:
  redis:
    image: "redis:5.0"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
  db:
    image: "postgres:11.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_DB: "${DATABASE_NAME}"
  web:
    build: .
    init: true
    ports:
      - "3000:3000"
    links:
      - redis
      - db
    depends_on:
      - db
      - redis
